server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: menu
          uri: http://localhost:8081
          predicates:
            - Path=/menus/** 
        - id: order
          uri: http://localhost:8082
          predicates:
            - Path=/orders/** 
        - id: make
          uri: http://localhost:8083
          predicates:
            - Path=/makes/*,*/cancelations/** 
        - id: notify
          uri: http://localhost:8084
          predicates:
            - Path=/notifies/** 
        - id: board
          uri: http://localhost:8085
          predicates:
            - Path= /boards/**
        - id: storage
          uri: http://localhost:8086
          predicates:
            - Path=/storageCancels/*,*/storageOrders/**            
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: menu
          uri: http://menu:8080
          predicates:
            - Path=/menus/** 
        - id: order
          uri: http://order:8080
          predicates:
            - Path=/orders/** 
        - id: make
          uri: http://make:8080
          predicates:
            - Path=/makes/*,*/cancelations/** 
        - id: notify
          uri: http://notify:8080
          predicates:
            - Path=/notifies/** 
        - id: board
          uri: http://board:8080
          predicates:
            - Path= /boards/**
        - id: storage
          uri: http://order:8080
          predicates:
            - Path=/storageCancels/*,*/storageOrders/**                
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
